jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package -Dmaven.test.skip --file pom.xml
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
      name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Dmaven.test.skip -s $GITHUB_WORKSPACE/settings.xml
name: QuickMedia
on:
  repository_dispatch:
    types: trigger-ga___mavenpublish.yml
